version: '2.2'

services:

  image-converter:
    image: esmailm90/imagination:latest
    container_name: image-converter
    mem_limit: 512m
    mem_reservation: 512m
    depends_on:
      - jaeger
      - httpbin
    environment:
      "Image:Configuration:TargetPixelsWidth": 1024
      "Image:Configuration:TargetPixelsHeight": 1024
      "Image:Configuration:TargetImageCompress": 60000
      "Image:Configuration:TargetImageCompressTolerance": 10000
      "Image:Configuration:MaxInputImageSize": 15000000
      "Image:Configuration:MinInputImageSize": 2000
    ports:
      - "5000:80"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268/tcp"
      - "14250:14250/tcp"
      - "16686:16686"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
